version: '2.3'
services:
  postgis:
    image: kartoza/postgis:9.6-2.4
    env_file:
      - ./env/kapany.env
    volumes:
      - /opt/kapany/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      vpcbr:
        ipv4_address: 10.6.0.2
  django:
    build: .
    env_file:
    - ./env/kapany.env
    command: bash /scripts/init_django.sh
    volumes:
    - ./server:/code
    - /opt/kapany/web/static:/static
    - /opt/kapany/web/media:/media
    expose:
    - 80
    links:
    - postgis:postgis
    depends_on:
    - postgis
    networks:
      vpcbr:
        ipv4_address: 10.6.0.3
  nginx:
    image: nginx:latest
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - /opt/kapany/web/www:/var/www
    - /opt/kapany/web/static:/static
    - /opt/kapany/web/media:/media
    ports:
    - 80:80
    depends_on:
    - django
    networks:
      vpcbr:
        ipv4_address: 10.6.0.4
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
      - subnet: 10.6.0.0/16
        gateway: 10.6.0.1